png(file="plot4.png")
plot(ts(subSetData$Global_active_power),ylab="Global Active Power(kilowatt)",xaxt='n',xlab="")
 axis(1,at=c(1,1440,2880),labels=c("Thu","Fri","Sat"))
 par(mfrow=c(2,2))
 plot(ts(subSetData$Global_active_power),ylab="Global Active Power(kilowatt)",xaxt='n',xlab="")
 axis(1,at=c(1,1440,2880),labels=c("Thu","Fri","Sat"))
 subSetData$Voltage<-as.numeric(subSetData$Voltage)
 plot(ts(subSetData$Voltage),ylab="Voltage",xaxt='n',xlab="datetime")
 axis(1,at=c(1,1440,2880),labels=c("Thu","Fri","Sat"))
 plot(ts(subSetData$Sub_metering_1),ylab="Energy Sub Metering",xlab='n',xaxt='n')
 lines(ts(subSetData$Sub_metering_2),col="red")
 lines(ts(subSetData$Sub_metering_3),col="blue")
 axis(1,at=c(1,1440,2880),labels=c("Thu","Fri","Sat"))
 subSetData$Global_reactive_power<-as.numeric(subSetData$Global_reactive_power)
 plot(ts(subSetData$Global_reactive_power),ylab="Global Reactive Power",xaxt='n',xlab="datetime")
 axis(1,at=c(1,1440,2880),labels=c("Thu","Fri","Sat"))
dev.off()